version: '2.4'

services:
  apache:
    build: apache
    restart: always
    oom_kill_disable: true
    volumes:
      - ./openeclass:/var/www/openeclass
      - ./puppies:/var/www/puppies
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/php.ini:/etc/php53/apache2/php.ini
    ports:
      - "${APACHE_PORT}:80"
  db:
    image: mysql:5.7
    restart: always
    oom_kill_disable: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "9906:3306"
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf
